-- Supabase Schema for Factory Maintenance Pro

-- 1. Users table
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  role TEXT NOT NULL,
  password TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Machines table
CREATE TABLE IF NOT EXISTS machines (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  type TEXT NOT NULL,
  model TEXT,
  serial_number TEXT,
  line TEXT,
  location TEXT,
  qr_code TEXT UNIQUE,
  status TEXT DEFAULT 'running',
  last_service TIMESTAMPTZ,
  purchase_date DATE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Maintenance table
CREATE TABLE IF NOT EXISTS maintenance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  machine_id BIGINT REFERENCES machines(id) ON DELETE CASCADE,
  type TEXT,
  technician_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  date DATE,
  checklist TEXT,
  description TEXT,
  status TEXT DEFAULT 'pending',
  accepted_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Breakdowns table
CREATE TABLE IF NOT EXISTS breakdowns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  machine_id BIGINT REFERENCES machines(id) ON DELETE CASCADE,
  issue TEXT,
  priority TEXT,
  reported_by_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  technician_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  status TEXT DEFAULT 'reported',
  reported_at TIMESTAMPTZ DEFAULT NOW(),
  resolved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Spare Parts table
CREATE TABLE IF NOT EXISTS spare_parts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  code TEXT UNIQUE NOT NULL,
  stock INTEGER DEFAULT 0,
  min_stock INTEGER DEFAULT 5,
  unit TEXT DEFAULT 'pcs',
  needle_size TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Spare Part Usage table
CREATE TABLE IF NOT EXISTS spare_part_usage (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  machine_id BIGINT REFERENCES machines(id) ON DELETE CASCADE,
  part_id BIGINT REFERENCES spare_parts(id) ON DELETE CASCADE,
  quantity INTEGER,
  technician_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  date TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Notifications table
CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  type TEXT, -- 'info', 'warning', 'error'
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Seed Initial Data (Optional - run in SQL Editor)
-- INSERT INTO users (name, email, role, password) VALUES ('Admin User', 'admin@factory.com', 'admin', 'password');
-- INSERT INTO users (name, email, role, password) VALUES ('John Manager', 'manager@factory.com', 'manager', 'password');
-- INSERT INTO users (name, email, role, password) VALUES ('Mike Tech', 'tech@factory.com', 'technician', 'password');
-- INSERT INTO users (name, email, role, password) VALUES ('Sarah Store', 'store@factory.com', 'store_manager', 'password');
-- INSERT INTO users (name, email, role, password) VALUES ('Bob Supervisor', 'supervisor@factory.com', 'supervisor', 'password');
